### ISSUE TITLE
更新する手順をどっかに記載してほしい

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/reading-vimrc#17]
http://lingr.com/room/vim/archives/2015/02/28#message-21354632

**Comment by haya14busa** [comment]
場所を書く候補としては
1. wiki
2. README
3. CONTRIBUTION.md

とかでしょうか. 手元で手軽に見たいという意味ではREADMEがよさげ?
`CONTRIBUTION.md` もありかなと思いましたがﾌﾟﾙﾘｸする前にみるものだったりして(?)ちょっと違う...?

**Comment by rbtnn** [comment]
はい、READMEでよいと思います。

**Comment by thinca** [comment]
:+1: :+1: :+1:
