### ISSUE TITLE
vimrcアンチパターンをどこかにまとめておいて欲しい

### ISSUE THREAD

**Issue by tyru** [vim-jp/reading-vimrc#19]
http://lingr.com/room/vim/archives/2016/02/04#message-23016013

> vimrcアンチパターンは正直vimrc勉強会のリポジトリのWikiでもいいのでどこかにまとめておいて欲しい

といった声が寄せられています。

**Comment by rbtnn** [comment]
随分前にまとめようとwiki作りましたけど、全然更新してませんね。

https://github.com/rbtnn/etc-about-vimscript/wiki/vimrc%E3%82%A2%E3%83%B3%E3%83%81%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3

**Comment by tyru** [comment]
@rbtnn ++
`g:vim_indent_cont`以外はこのリポジトリのWikiに持ってきて良さそうです。

**Comment by rbtnn** [comment]
@tyru とりあえずそのまま移転しました。

https://github.com/vim-jp/reading-vimrc/wiki/vimrc%E3%82%A2%E3%83%B3%E3%83%81%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3

**Comment by tyru** [comment]
ありがとうございます！
