### ISSUE TITLE
ロゴがでかい

### ISSUE THREAD

**Issue by thinca** [vim-jp/reading-vimrc#25]
トップ画面に表示されるロゴが、容量約1MB(1,055,823 バイト)、サイズが 3,788px × 910px (650px × 156px で表示) と、Web サイトに載せるものにしてはやけに大きい。
いい感じに小さくしたい。

**Comment by thinca** [comment]
@Tatsuki-I すいませんがお願いできますか?

**Comment by Tatsuki-I** [comment]
@thinca どのぐらいのサイズにすればいいでしょうか？

**Comment by mattn** [comment]
http://vim-jp.org/reading-vimrc/archive/index.html

404 のページがある様です。

**Comment by thinca** [comment]
@Tatsuki-I 
私の環境だと 650px × 156px で表示されているようなので、これが環境依存とかでないのならコレくらいのサイズでいいと思います。色数や不要なメタデータなんかも一応見てみてください (この辺り詳しくないのでどう最適化するのがいいのかよくわかってませんが…)

@mattn 
ほんとだ。ありがとうございます。

@Tatsuki-I 
トップページ以外からの log の参照がうまくできてないっぽいです。確か相対パスではなくてページルートを示す文字列(テンプレート変数かな?)が jekyll で使えた気がするので(他にやってる場所があった気がする)、やってみてもらえますか?
わからなかったらまた聞いてください。

**Comment by Tatsuki-I** [comment]
@thinca 
分かりました。対応したいと思います。
@mattn 
報告ありがとうございます。

**Comment by thinca** [comment]
404 については別 Issue 立てたので、こちらは閉じます。
